### PR TITLE
Add possibility to execute postprocessing script with changed objects

### PR DESCRIPTION
**Pull request by viktordick**

### CODE REVIEW

**Review by jan-jockusch — APPROVED** [review]
LGTM!

**Comment by Wiseqube** [comment]
If we have a postprocessing script for zodbsync pick we should consider also adding the commits which were picked?

**Comment by viktordick** [comment]
@jan-jockusch Thanks for the review, but this is still WIP. Tests are missing ;)

@Wiseqube: This is not only applied when picking commits, but also, for example, when resetting or using `zodbsync exec` with some weird git command. So I am not sure how to cover the rather generic case.
As a compromise, I suggest changing the protocol that we speak with the postprocessing to JSON. Then we can later extend it.

**Review by Wiseqube — APPROVED** [review]
LGTM

**Pull request merged**
