### PR TITLE
Fix layer-update for differing last elements

### PR DESCRIPTION
**Pull request by viktordick**

### CODE REVIEW

**Review by Wiseqube — APPROVED** [review]
Code LGTM. Maybe we should still add a Test for this feature

**Comment by viktordick** [comment]
> Code LGTM. Maybe we should still add a Test for this feature

Done. Did not want to try and setup a full layer-update scenario for this case, so I pulled the relevant algorithm out into its own helper function and added a test there.

**Review by Wiseqube — APPROVED** [review]
OK, still LGTM

**Comment by viktordick** [comment]
@Wiseqube Did you push your last commit on the wrong branch? I guess it does not really matter, I will merge it together with that.

**Pull request merged**
