### PR TITLE
Refactor scripts into entry points to be usable with zc.buildout >= 3.

### PR DESCRIPTION
**Pull request by icemac**
`zc.buildout >=3` seems to ignore the `scripts` option in `setup.py`, so I refactored it into a entry-points which works successfully.

### CODE REVIEW

**Review by viktordick — APPROVED** [review]
LGTM, thank you!

Unfortunately, I just merged another PR, so you will need to rebase this and resolve a trivial conflict in the CHANGELOG.

**Review by viktordick — CHANGES_REQUESTED** [review]
Although it seems that the tests are failing with this and need to be adjusted.

**Comment by viktordick** [comment]
It seems it will be sufficient to remove the `bin` path from the `flake8` call in `tox.ini`.
(to be clear: Only the py3 tests need to run through. We still need to officially drop py2 support here, but we have not included this in a py2 build for a year now and I am actually unable to run the py2 tests on my Ubuntu 22)

**Comment by icemac** [comment]
@viktordick Thank you for looking at this PR. I (hopefully) fixed the necessary bits.

**Review by viktordick — APPROVED** [review]
LGTM

**Pull request merged**
